apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  namespace: default
  labels:
    app: front
spec:
  replicas: 2
  selector:
    matchLabels:
      name: front
  template:
    metadata:
      labels:
        name: front
    spec:

      containers:
      - name: front
        image: 109366565312.dkr.ecr.us-east-2.amazonaws.com/kontinu/python-expert:c511a10

        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 1
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 1


        env:
        - name: NEXT_URL
          value: http://middle/api
        resources: {}

---
kind: Service
apiVersion: v1
metadata:
  name:  front
spec:
  selector:
    name: front
  type: LoadBalancer
  ports:
  - name:  web
    port:  80
    targetPort:  http


