apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigmap
  labels:
    app: myapplication
data:
  FOO: "from configmap"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigmap
  labels:
    app: myapplication
data:
  my-properties-file.toml: |
    # yaml file
    key=value
    otra=llave
    [global]
    hello=global

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigmap
  labels:
    app: myapplication
data:
  my-key: my-value
  my-properties-file.yaml: |
    # yaml file
    key: value



